name: C++ CI for hello world

on:
  push:
    branches: [main]  # limit to main branch

jobs:
  build-and-test-helloworld:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 00_helloworld/cpp
    steps:
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: make
        run: make
      - name: make test
        run: make test
