name: C++ CI for hello world

on:
  push:
    branches: [main]  # limit to main branch

jobs:
  build-and-test-helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: make
        run: make helloworld
      - name: make test-helloworld
        run: make test
