# This is an example for lab1

name: Lab1 Sample Run

on:
  push:
    branches: [main]  # limit to main branch

jobs:
  build-lab1-gcc48:
    runs-on: ubuntu-latest
    
    steps:
      - name: compiler version
        run: |
            gcc --version
            g++ --version
      - uses: actions/checkout@v2
      - name: build
        run: cd 01_primitives && g++ file_in.cpp -std=c++98 -o file_in && ./file_in
