# This is an example for lab1
name: Lab1 Sample Run

on:
  push:
    branches: [main]  # limit to main branch

jobs:
  build-lab1:
    runs-on: ubuntu-latest
    container:
      image: scientificlinux/sl:7
    
    steps:
      - uses: actions/checkout@v2
      - name: g++ version
        run: g++ -version
      - name: make
        run: make lab1
